name: Build and Deploy Server-GO to VPS

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Change to project directory
        working-directory: source/server-go
        run: echo "Moved to source/server-go"

      - name: Install dependencies
        working-directory: source/server-go
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go mod tidy

      - name: Build binary
        working-directory: source/server-go
        run: make build-arm64

      # - name: Generate OpenAPI Docs
      #   working-directory: source/server-go
      #   run: |
      #     go install github.com/swaggo/swag/cmd/swag@latest
      #     swag init --dir ./cmd/server --output ./internal/docs

      - name: Set deployment config
        id: config
        run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "${{ secrets.PROD_SSH_KEY }}" > /tmp/id_rsa
          echo "HOST=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.PROD_USER }}" >> $GITHUB_ENV
          echo "KEY=/tmp/id_rsa" >> $GITHUB_ENV
          echo "TARGET=~/app/server-go" >> $GITHUB_ENV
        else
          echo "${{ secrets.DEV_SSH_KEY }}" > /tmp/id_rsa
          echo "HOST=${{ secrets.DEV_HOST }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.DEV_USER }}" >> $GITHUB_ENV
          echo "KEY=/tmp/id_rsa" >> $GITHUB_ENV
          echo "TARGET=~/dev/server-go" >> $GITHUB_ENV
        fi
        chmod 600 /tmp/id_rsa
      shell: bash

      - name: Copy binary
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          port: 22
          source: "./source/server-go/bin/api-server-arm64"
          target: "${{ env.TARGET }}/api-server"
          strip_components: 3

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          port: 22
          script: |
            systemctl --user restart api-server
