name: Build and Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # container:
    #   image: luri/ssh-client:latest

    env:
      SSH_USER: ${{ secrets.USER_NAME }}
      SSH_HOST: ${{ secrets.HOST_NAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      TARGET_DIR: "~/app/server-go"
      BINARY_NAME: "api-server"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Go binary
        run: |
          cd source/server-go
          go mod tidy
          mkdir -p bin
          go build -o bin/$BINARY_NAME ./cmd/server

      - name: Prepare deploy script
        run: |
          cat << 'EOF' > deploy.sh
          #!/bin/sh

          set -e
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

          LOCAL_BINARY="source/server-go/bin/$BINARY_NAME"
          REMOTE_TMP="$TARGET_DIR/$BINARY_NAME.tmp"
          REMOTE_FINAL="$TARGET_DIR/$BINARY_NAME"

          LOCAL_HASH=$(sha256sum "$LOCAL_BINARY" | awk '{print $1}')
          scp -i ~/.ssh/id_rsa "$LOCAL_BINARY" "$SSH_USER@$SSH_HOST:$REMOTE_TMP"
          REMOTE_HASH=$(ssh -i ~/.ssh/id_rsa "$SSH_USER@$SSH_HOST" "sha256sum $REMOTE_TMP | awk '{print \$1}'")

          echo "Local  : $LOCAL_HASH"
          echo "Remote : $REMOTE_HASH"

          if [ "$LOCAL_HASH" = "$REMOTE_HASH" ]; then
            echo "✅ Hash cocok, deploy dilanjutkan."
            ssh -i ~/.ssh/id_rsa "$SSH_USER@$SSH_HOST" "
              mv $REMOTE_TMP $REMOTE_FINAL &&
              chmod +x $REMOTE_FINAL &&
              systemctl --user restart $BINARY_NAME
            "
          else
            echo "❌ Hash tidak cocok, deploy dibatalkan."
            exit 1
          fi
          EOF

          chmod +x deploy.sh

      - name: Run deploy
        run: ./deploy.sh
