name: Build and Deploy Server-GO to VPS

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Change to project directory
        working-directory: source/server-go
        run: echo "Moved to source/server-go"

      - name: Install dependencies
        working-directory: source/server-go
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go mod tidy

      - name: Build binary
        working-directory: source/server-go
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            make build-arm64
            echo "BUILD_OUTPUT=api-server-arm64" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" = "refs/heads/development" ]; then
            make build-arm64
            echo "BUILD_OUTPUT=api-server-arm64" >> $GITHUB_ENV
          fi

      - name: Copy binary to production (main branch)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          source: "./source/server-go/bin/${{ env.BUILD_OUTPUT }}"
          target: "~/app/server-go/api-server"
          strip_components: 3

      - name: Restart production service
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            systemctl --user restart api-server

      - name: Copy binary to development
        if: github.ref == 'refs/heads/development'
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: 22
          source: "./source/server-go/bin/${{ env.BUILD_OUTPUT }}"
          target: "~/app/server-go/api-server"
          strip_components: 3

      - name: Restart development service
        if: github.ref == 'refs/heads/development'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: 22
          script: |
            systemctl --user restart api-server