name: Build and Deploy Server-GO to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Change to project directory
        working-directory: source/server-go
        run: echo "Moved to source/server-go"

      - name: Install dependencies
        working-directory: source/server-go
        run: go mod tidy

      - name: Build binary
        working-directory: source/server-go
        run: go build -o bin/api-server ./cmd/server

      # - name: Generate OpenAPI Docs
      #   working-directory: source/server-go
      #   run: |
      #     go install github.com/swaggo/swag/cmd/swag@latest
      #     swag init --dir ./cmd/server --output ./internal/docs

      - name: Deploy and Restart
        uses: docker://luri/ssh-client:latest
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.USER_NAME }}
          SSH_HOST: ${{ secrets.HOST_NAME }}
          TARGET_DIR: "~/app/server-go"
        with:
          entrypoint: /bin/sh
          args: |
            -c "
            mkdir -p ~/.ssh &&
            echo \"\$SSH_PRIVATE_KEY\" > ~/.ssh/id_rsa &&
            chmod 600 ~/.ssh/id_rsa &&
            echo -e \"Host *\\n\\tStrictHostKeyChecking no\\n\" > ~/.ssh/config &&
            scp -i ~/.ssh/id_rsa source/server-go/bin/api-server \$SSH_USER@\$SSH_HOST:\$TARGET_DIR &&
            ssh -i ~/.ssh/id_rsa \$SSH_USER@\$SSH_HOST 'systemctl --user restart api-server'
            "
